FROM python 
# COPY backend.env /BACKEND/.env
COPY FRONTEND /FRONTEND
WORKDIR /FRONTEND

# # # copy module files first so that they don't need to be downloaded again if no change
# # COPY go.* ./
# # RUN go mod download
# # RUN go mod verify

# # copy source files and build the binary
# RUN make build

CMD ["python3", "-m", "http.server", "1337"]
