FROM python 
COPY frontend.env  /FRONTEND/.env
COPY entrypoints/entrypoint_frontend.sh /FRONTEND/entrypoint.sh
COPY FRONTEND /FRONTEND
WORKDIR /FRONTEND

# # # copy module files first so that they don't need to be downloaded again if no change
# # COPY go.* ./
# # RUN go mod download
# # RUN go mod verify

# # copy source files and build the binary
# RUN make build

CMD ["./entrypoint.sh"]
